### PR TITLE
Update README.md to reflect project status

### PR DESCRIPTION
**Pull request by jteplitz**

### CODE REVIEW

**Comment by d11wtq** [comment]
This won't get merged as the author has not been seen in a couple of years.

**Comment by jteplitz602** [comment]
Ah. That's unfortunate.

**Comment by wsdjeg** [comment]
@d11wtq 
is there any way to remove the fork,now the project can not be search by github,also can not search code in the fork repo!!,it is very hard to read the src code of the fork repo!

**Comment by wsdjeg** [comment]
my god~ thanks @kien 
now so many people work for this plugin

**Comment by d11wtq** [comment]
Thanks @kien!

**Pull request merged**
